<a href="https://colab.research.google.com/github/priyanshu87694/Machine-Learning-sklearn/blob/master/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Imports

In [257]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [258]:
data = pd.read_csv('/content/car.data')
print(data.head())

  buying  maint doors persons lug_boots safety  class
0  vhigh  vhigh     2       2     small    low  unacc
1  vhigh  vhigh     2       2     small    med  unacc
2  vhigh  vhigh     2       2     small   high  unacc
3  vhigh  vhigh     2       2       med    low  unacc
4  vhigh  vhigh     2       2       med    med  unacc


In [265]:
X = data[['buying', 'maint', 'safety']]
print(X.head())
print()
y = data[['class']]
print(y.head())

  buying  maint safety
0  vhigh  vhigh    low
1  vhigh  vhigh    med
2  vhigh  vhigh   high
3  vhigh  vhigh    low
4  vhigh  vhigh    med

   class
0  unacc
1  unacc
2  unacc
3  unacc
4  unacc


#### Data conversion

In [266]:
le = LabelEncoder()
X = X.values
for i in range(len(X[0])):
  X[:, i] = le.fit_transform(X[:, i])
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [267]:
# converting y
label_mapping = {
    'unacc': 0,
    'acc': 1,
    'good': 2,
    'vgood': 3
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


### Create and Train the model

In [272]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)
# model
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')
knn.fit(Xtrain, ytrain)
prediction = knn.predict(Xtest)
accuracy = metrics.accuracy_score(ytest, prediction)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [273]:
print('prediction: ', prediction)
print('accuracy: ', accuracy)

prediction:  [0 0 1 0 0 1 0 0 0 0 1 2 1 0 3 0 0 0 0 1 0 0 1 3 0 0 0 0 0 3 0 0 0 3 0 0 1
 1 3 0 0 3 0 0 0 0 0 0 0 0 0 1 3 0 1 0 0 0 1 0 0 0 1 0 0 1 0 2 0 1 0 0 0 0
 1 1 0 0 1 0 3 1 0 0 0 1 0 0 0 0 0 0 0 3 0 2 0 0 0 2 0 0 0 0 0 0 3 3 0 0 1
 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 3 0 1 0 0 2 0 3 0 0 1 1 3 0 2
 0 0 0 1 0 3 0 1 0 0 1 0 0 0 0 0 2 1 1 1 1 0 3 3 1 0 1 0 0 1 0 0 1 2 3 0 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 2 0 1 0 0 0 1 0 0 0 2 1 0 0 0 0 0 0
 2 3 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 2 3 0 0 0
 1 0 0 1 0 0 0 0 1 2 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 2 0 0 0 0 3 1 1 0 0
 1 0 0 0 1 1 1 1 3 0 0 1 0 0 0 3 0 2 0 0 0 0 0 0 2 0 0 1 0 0 3 0 1 0 0 0 0
 3 0 0 0 1 0 1 1 0 1 0 0 0]
accuracy:  0.7543352601156069
